name: Bug report
labels: [bug]
description: Report a bug to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por abrir um bug! Preencha os itens abaixo para acelerar a correção.
  - type: input
    id: summary
    attributes:
      label: Resumo
      description: Descreva o problema em 1-2 frases.
      placeholder: Ex. Erro ao rodar make test no Node 24.x
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos para reproduzir o problema
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Ambiente
      placeholder: Ex. macOS 14.6, Node 24.7.0
  - type: textarea
    id: logs
    attributes:
      label: Logs / prints relevantes
      render: shell